language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - rustup target add wasm32-unknown-unknown
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

script:
  - cargo build --verbose --all
  - cargo test --verbose --tests --features "test"
  - cargo test --verbose --doc
  - cargo check --target wasm32-unknown-unknown
  - wasm-pack test --node